# Header
menu:
  Home: /
  Archives: /archives
rss:

# Content
excerpt_link: 続きを読む
fancybox: true

# Sidebar
sidebar: right
widgets:
- tag
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon:
twitter: gabalist
google_plus:
fb_admins:
fb_app_id:

search: false
github: kazsw